# Generated by Django 5.2.6 on 2025-10-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Only used for BOGO-type coupons. Leave blank for site-wide coupons.', to='core.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('bogo_50', 'BOGO 50% Off')], max_length=20),
        ),
    ]
