# Generated by Django 5.2.6 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coupon_applicable_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_new_user_only',
            field=models.BooleanField(default=False, help_text='If checked, this coupon can only be used by new users (users with no previous orders).'),
        ),
    ]
